### ISSUE TITLE
用户主页视频超过100个，工具仅识别36个

### ISSUE THREAD

**Issue by cato1718** [kun775/douyinhelper#6]
https://v.douyin.com/RVWUTQM/
该博主视频超过100+，使用工具仅可识别36个
![image](https://user-images.githubusercontent.com/8504585/143179486-deff7436-5cb5-43c2-91f6-22d7d39c1e6d.png)

**Comment by kun775** [comment]
https://www.52pojie.cn/forum.php?mod=viewthread&tid=1450767&highlight=B%D5%BE
试试这个工具



在 2021-11-24 13:21:34，"Cato" ***@***.***> 写道：

https://v.douyin.com/RVWUTQM/
该博主视频超过100+，使用工具仅可识别36个


—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cato1718** [comment]
可能是界面显示的问题，其实是把当前100+的视频都下载下来了，给作者点赞~
